# Generated by Django 3.2.13 on 2022-04-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='課程/班級名稱')),
                ('ctype', models.IntegerField(choices=[(0, '課程'), (1, '班級')], verbose_name='類型')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=16, verbose_name='學號')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('course', models.ManyToManyField(related_name='students', to='course.Course')),
            ],
        ),
    ]
